TRI_LAYER_ENABLE = yes

BOOTLOADER = caterina
# to get .uf2 file
CONVERT_TO=promicro_rp2040

VIA_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
ENCODER_ENABLE = yes
LTO_ENABLE = yes
OLED_ENABLE = yes
